/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'voteId' : IDL.Nat,
  'author' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CustomOptionAlloc = IDL.Record({
  'pct' : IDL.Nat,
  'optionIndex' : IDL.Nat,
});
export const VoteType = IDL.Variant({
  'ICP' : IDL.Null,
  'BITTYICP' : IDL.Null,
});
export const CustomProposal = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'closeTime' : IDL.Int,
  'voteType' : VoteType,
  'totalVoteAmount' : IDL.Text,
  'description' : IDL.Text,
  'isFinalized' : IDL.Bool,
  'options' : IDL.Vec(IDL.Text),
  'openTime' : IDL.Int,
});
export const MonthlyVote = IDL.Record({
  'id' : IDL.Nat,
  'month' : IDL.Nat,
  'closeTime' : IDL.Int,
  'voteType' : VoteType,
  'totalVoteAmount' : IDL.Text,
  'year' : IDL.Nat,
  'isFinalized' : IDL.Bool,
  'openTime' : IDL.Int,
});
export const RewardTransaction = IDL.Record({
  'id' : IDL.Nat,
  'recipient' : IDL.Text,
  'voteId' : IDL.Nat,
  'timestamp' : IDL.Int,
  'tokenType' : VoteType,
  'amount' : IDL.Nat,
  'voteTitle' : IDL.Text,
  'proposalId' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CustomProposalMeta = IDL.Record({
  'destinationAddress' : IDL.Text,
  'voteAmount' : IDL.Text,
  'proposalId' : IDL.Nat,
});
export const CustomRewardsPoolEntry = IDL.Record({
  'distributed' : IDL.Bool,
  'voteType' : VoteType,
  'losingOptionPct' : IDL.Nat,
  'losingOptionLabel' : IDL.Text,
  'proposalId' : IDL.Nat,
  'poolAmount' : IDL.Text,
});
export const CustomVoteAllocation = IDL.Record({
  'votingPower' : IDL.Nat,
  'allocations' : IDL.Vec(CustomOptionAlloc),
  'proposalId' : IDL.Nat,
  'voterPrincipal' : IDL.Text,
});
export const CustomVoteResult = IDL.Record({
  'optionLabel' : IDL.Text,
  'totalWeightedPct' : IDL.Nat,
  'optionIndex' : IDL.Nat,
  'voterCount' : IDL.Nat,
});
export const PendingDistribution = IDL.Record({
  'title' : IDL.Text,
  'voteType' : VoteType,
  'voteId' : IDL.Nat,
  'amountNeeded' : IDL.Text,
  'isCustom' : IDL.Bool,
  'proposalId' : IDL.Nat,
});
export const RewardsPoolEntry = IDL.Record({
  'distributed' : IDL.Bool,
  'voteType' : VoteType,
  'voteId' : IDL.Nat,
  'losingOptionPct' : IDL.Nat,
  'losingOptionLabel' : IDL.Text,
  'poolAmount' : IDL.Text,
});
export const VoteAllocation = IDL.Record({
  'votingPower' : IDL.Nat,
  'pctA' : IDL.Nat,
  'pctB' : IDL.Nat,
  'pctC' : IDL.Nat,
  'voteId' : IDL.Nat,
  'voterPrincipal' : IDL.Text,
});
export const VoteResult = IDL.Record({
  'optionLabel' : IDL.Text,
  'totalWeightedPct' : IDL.Nat,
  'voterCount' : IDL.Nat,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAnnouncement' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Opt(Announcement)],
      [],
    ),
  'addChatMessage' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Opt(ChatMessage)],
      [],
    ),
  'adminLogin' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'adminResetVerifiedWallets' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'autoFinalizeExpired' : IDL.Func([], [], []),
  'castCustomVote' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Vec(CustomOptionAlloc), IDL.Nat],
      [IDL.Bool],
      [],
    ),
  'castSplitVote' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Bool],
      [],
    ),
  'confirmWalletVerification' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'createCustomProposal' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        VoteType,
        IDL.Vec(IDL.Text),
        IDL.Int,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Opt(CustomProposal)],
      [],
    ),
  'deleteAnnouncement' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'distributeCustomRewards' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [
        IDL.Record({
          'errors' : IDL.Vec(IDL.Text),
          'success' : IDL.Bool,
          'transferCount' : IDL.Nat,
        }),
      ],
      [],
    ),
  'distributeRewards' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [
        IDL.Record({
          'errors' : IDL.Vec(IDL.Text),
          'success' : IDL.Bool,
          'transferCount' : IDL.Nat,
        }),
      ],
      [],
    ),
  'finalizeCustomProposal' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'finalizeVote' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'getActiveVotes' : IDL.Func([], [IDL.Vec(MonthlyVote)], []),
  'getAdminConfig' : IDL.Func(
      [],
      [
        IDL.Record({
          'gamesWallet' : IDL.Text,
          'neuronTopupAddress' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getAllRewardTransactions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(RewardTransaction)],
      [],
    ),
  'getAllVotes' : IDL.Func([], [IDL.Vec(MonthlyVote)], []),
  'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getBittyUsdPrice' : IDL.Func([], [IDL.Text], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCanisterBalance' : IDL.Func(
      [],
      [IDL.Record({ 'icpE8s' : IDL.Nat, 'bittyE8s' : IDL.Nat })],
      [],
    ),
  'getChatMessages' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
  'getCustomProposalMeta' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(CustomProposalMeta)],
      ['query'],
    ),
  'getCustomProposals' : IDL.Func([], [IDL.Vec(CustomProposal)], ['query']),
  'getCustomRewardsPools' : IDL.Func(
      [],
      [IDL.Vec(CustomRewardsPoolEntry)],
      ['query'],
    ),
  'getCustomVoteAllocations' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(CustomVoteAllocation)],
      ['query'],
    ),
  'getCustomVoteResults' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(CustomVoteResult)],
      ['query'],
    ),
  'getIcpUsdPrice' : IDL.Func([], [IDL.Text], []),
  'getManualBalances' : IDL.Func(
      [],
      [
        IDL.Record({
          'icp' : IDL.Text,
          'fund' : IDL.Text,
          'bittyPriceUsd' : IDL.Text,
          'bitty' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getMyRewardTransactions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(RewardTransaction)],
      ['query'],
    ),
  'getMyVerifiedWallets' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getPendingDistributions' : IDL.Func(
      [],
      [IDL.Vec(PendingDistribution)],
      ['query'],
    ),
  'getRewardsPools' : IDL.Func([], [IDL.Vec(RewardsPoolEntry)], ['query']),
  'getTotalRewardsDistributed' : IDL.Func(
      [],
      [IDL.Record({ 'totalICP' : IDL.Nat, 'totalBITTY' : IDL.Nat })],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVoteAllocations' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(VoteAllocation)],
      ['query'],
    ),
  'getVoteResults' : IDL.Func([IDL.Nat], [IDL.Vec(VoteResult)], ['query']),
  'getWalletOwner' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'hasVotedOnCustomProposal' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
  'hasVotedOnVote' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], ['query']),
  'initWalletVerification' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isExternalWalletClaimed' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'markCustomRewardsDistributed' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Bool],
      [],
    ),
  'markRewardsDistributed' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'retryPendingDistributions' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setCustomProposalAmount' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'setGamesWallet' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'setManualBalances' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'setManualBittyPrice' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'setManualFundBalance' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'setNeuronTopupAddress' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'setVoteAmount' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Bool], []),
  'setVoteAmountFromTreasury' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'transformHttpResponse' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unverifyWallet' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'updateAnnouncement' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'verifyExternalWallet' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'voteId' : IDL.Nat,
    'author' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CustomOptionAlloc = IDL.Record({
    'pct' : IDL.Nat,
    'optionIndex' : IDL.Nat,
  });
  const VoteType = IDL.Variant({ 'ICP' : IDL.Null, 'BITTYICP' : IDL.Null });
  const CustomProposal = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'closeTime' : IDL.Int,
    'voteType' : VoteType,
    'totalVoteAmount' : IDL.Text,
    'description' : IDL.Text,
    'isFinalized' : IDL.Bool,
    'options' : IDL.Vec(IDL.Text),
    'openTime' : IDL.Int,
  });
  const MonthlyVote = IDL.Record({
    'id' : IDL.Nat,
    'month' : IDL.Nat,
    'closeTime' : IDL.Int,
    'voteType' : VoteType,
    'totalVoteAmount' : IDL.Text,
    'year' : IDL.Nat,
    'isFinalized' : IDL.Bool,
    'openTime' : IDL.Int,
  });
  const RewardTransaction = IDL.Record({
    'id' : IDL.Nat,
    'recipient' : IDL.Text,
    'voteId' : IDL.Nat,
    'timestamp' : IDL.Int,
    'tokenType' : VoteType,
    'amount' : IDL.Nat,
    'voteTitle' : IDL.Text,
    'proposalId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CustomProposalMeta = IDL.Record({
    'destinationAddress' : IDL.Text,
    'voteAmount' : IDL.Text,
    'proposalId' : IDL.Nat,
  });
  const CustomRewardsPoolEntry = IDL.Record({
    'distributed' : IDL.Bool,
    'voteType' : VoteType,
    'losingOptionPct' : IDL.Nat,
    'losingOptionLabel' : IDL.Text,
    'proposalId' : IDL.Nat,
    'poolAmount' : IDL.Text,
  });
  const CustomVoteAllocation = IDL.Record({
    'votingPower' : IDL.Nat,
    'allocations' : IDL.Vec(CustomOptionAlloc),
    'proposalId' : IDL.Nat,
    'voterPrincipal' : IDL.Text,
  });
  const CustomVoteResult = IDL.Record({
    'optionLabel' : IDL.Text,
    'totalWeightedPct' : IDL.Nat,
    'optionIndex' : IDL.Nat,
    'voterCount' : IDL.Nat,
  });
  const PendingDistribution = IDL.Record({
    'title' : IDL.Text,
    'voteType' : VoteType,
    'voteId' : IDL.Nat,
    'amountNeeded' : IDL.Text,
    'isCustom' : IDL.Bool,
    'proposalId' : IDL.Nat,
  });
  const RewardsPoolEntry = IDL.Record({
    'distributed' : IDL.Bool,
    'voteType' : VoteType,
    'voteId' : IDL.Nat,
    'losingOptionPct' : IDL.Nat,
    'losingOptionLabel' : IDL.Text,
    'poolAmount' : IDL.Text,
  });
  const VoteAllocation = IDL.Record({
    'votingPower' : IDL.Nat,
    'pctA' : IDL.Nat,
    'pctB' : IDL.Nat,
    'pctC' : IDL.Nat,
    'voteId' : IDL.Nat,
    'voterPrincipal' : IDL.Text,
  });
  const VoteResult = IDL.Record({
    'optionLabel' : IDL.Text,
    'totalWeightedPct' : IDL.Nat,
    'voterCount' : IDL.Nat,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Opt(Announcement)],
        [],
      ),
    'addChatMessage' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Opt(ChatMessage)],
        [],
      ),
    'adminLogin' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'adminResetVerifiedWallets' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'autoFinalizeExpired' : IDL.Func([], [], []),
    'castCustomVote' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Vec(CustomOptionAlloc), IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'castSplitVote' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'confirmWalletVerification' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'createCustomProposal' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          VoteType,
          IDL.Vec(IDL.Text),
          IDL.Int,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Opt(CustomProposal)],
        [],
      ),
    'deleteAnnouncement' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'distributeCustomRewards' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [
          IDL.Record({
            'errors' : IDL.Vec(IDL.Text),
            'success' : IDL.Bool,
            'transferCount' : IDL.Nat,
          }),
        ],
        [],
      ),
    'distributeRewards' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [
          IDL.Record({
            'errors' : IDL.Vec(IDL.Text),
            'success' : IDL.Bool,
            'transferCount' : IDL.Nat,
          }),
        ],
        [],
      ),
    'finalizeCustomProposal' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'finalizeVote' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'getActiveVotes' : IDL.Func([], [IDL.Vec(MonthlyVote)], []),
    'getAdminConfig' : IDL.Func(
        [],
        [
          IDL.Record({
            'gamesWallet' : IDL.Text,
            'neuronTopupAddress' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getAllRewardTransactions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(RewardTransaction)],
        [],
      ),
    'getAllVotes' : IDL.Func([], [IDL.Vec(MonthlyVote)], []),
    'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getBittyUsdPrice' : IDL.Func([], [IDL.Text], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCanisterBalance' : IDL.Func(
        [],
        [IDL.Record({ 'icpE8s' : IDL.Nat, 'bittyE8s' : IDL.Nat })],
        [],
      ),
    'getChatMessages' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
    'getCustomProposalMeta' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(CustomProposalMeta)],
        ['query'],
      ),
    'getCustomProposals' : IDL.Func([], [IDL.Vec(CustomProposal)], ['query']),
    'getCustomRewardsPools' : IDL.Func(
        [],
        [IDL.Vec(CustomRewardsPoolEntry)],
        ['query'],
      ),
    'getCustomVoteAllocations' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(CustomVoteAllocation)],
        ['query'],
      ),
    'getCustomVoteResults' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(CustomVoteResult)],
        ['query'],
      ),
    'getIcpUsdPrice' : IDL.Func([], [IDL.Text], []),
    'getManualBalances' : IDL.Func(
        [],
        [
          IDL.Record({
            'icp' : IDL.Text,
            'fund' : IDL.Text,
            'bittyPriceUsd' : IDL.Text,
            'bitty' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getMyRewardTransactions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(RewardTransaction)],
        ['query'],
      ),
    'getMyVerifiedWallets' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getPendingDistributions' : IDL.Func(
        [],
        [IDL.Vec(PendingDistribution)],
        ['query'],
      ),
    'getRewardsPools' : IDL.Func([], [IDL.Vec(RewardsPoolEntry)], ['query']),
    'getTotalRewardsDistributed' : IDL.Func(
        [],
        [IDL.Record({ 'totalICP' : IDL.Nat, 'totalBITTY' : IDL.Nat })],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVoteAllocations' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(VoteAllocation)],
        ['query'],
      ),
    'getVoteResults' : IDL.Func([IDL.Nat], [IDL.Vec(VoteResult)], ['query']),
    'getWalletOwner' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'hasVotedOnCustomProposal' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'hasVotedOnVote' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], ['query']),
    'initWalletVerification' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isExternalWalletClaimed' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'markCustomRewardsDistributed' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'markRewardsDistributed' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'retryPendingDistributions' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setCustomProposalAmount' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'setGamesWallet' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'setManualBalances' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'setManualBittyPrice' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'setManualFundBalance' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'setNeuronTopupAddress' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'setVoteAmount' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Bool], []),
    'setVoteAmountFromTreasury' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'transformHttpResponse' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unverifyWallet' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'updateAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'verifyExternalWallet' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };