/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'author' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'proposalId' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Proposal = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Int,
  'title' : IDL.Text,
  'endTime' : IDL.Int,
  'description' : IDL.Text,
  'isOpen' : IDL.Bool,
  'options' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Vote = IDL.Record({
  'weight' : IDL.Nat,
  'optionIndex' : IDL.Nat,
  'proposalId' : IDL.Nat,
  'voterPrincipal' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAnnouncement' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Opt(Announcement)],
      [],
    ),
  'addChatMessage' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Opt(ChatMessage)],
      [],
    ),
  'adminLogin' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'castVote' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'closeProposal' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'createProposal' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Opt(Proposal)],
      [],
    ),
  'deleteAnnouncement' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatMessages' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
  'getManualBalances' : IDL.Func(
      [],
      [
        IDL.Record({
          'icp' : IDL.Text,
          'fund' : IDL.Text,
          'bittyPriceUsd' : IDL.Text,
          'bitty' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getProposals' : IDL.Func([], [IDL.Vec(Proposal)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVotesForProposal' : IDL.Func([IDL.Nat], [IDL.Vec(Vote)], ['query']),
  'hasVoted' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setManualBalances' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'setManualBittyPrice' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'setManualFundBalance' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateAnnouncement' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'author' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'proposalId' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Proposal = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Int,
    'title' : IDL.Text,
    'endTime' : IDL.Int,
    'description' : IDL.Text,
    'isOpen' : IDL.Bool,
    'options' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Vote = IDL.Record({
    'weight' : IDL.Nat,
    'optionIndex' : IDL.Nat,
    'proposalId' : IDL.Nat,
    'voterPrincipal' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Opt(Announcement)],
        [],
      ),
    'addChatMessage' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Opt(ChatMessage)],
        [],
      ),
    'adminLogin' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'castVote' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'closeProposal' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'createProposal' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Opt(Proposal)],
        [],
      ),
    'deleteAnnouncement' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatMessages' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
    'getManualBalances' : IDL.Func(
        [],
        [
          IDL.Record({
            'icp' : IDL.Text,
            'fund' : IDL.Text,
            'bittyPriceUsd' : IDL.Text,
            'bitty' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getProposals' : IDL.Func([], [IDL.Vec(Proposal)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVotesForProposal' : IDL.Func([IDL.Nat], [IDL.Vec(Vote)], ['query']),
    'hasVoted' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setManualBalances' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'setManualBittyPrice' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'setManualFundBalance' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'updateAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };