/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'timestamp' : bigint,
}
export interface ChatMessage {
  'id' : bigint,
  'author' : string,
  'message' : string,
  'timestamp' : bigint,
  'proposalId' : bigint,
}
export interface Proposal {
  'id' : bigint,
  'startTime' : bigint,
  'title' : string,
  'endTime' : bigint,
  'description' : string,
  'isOpen' : boolean,
  'options' : Array<string>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vote {
  'weight' : bigint,
  'optionIndex' : bigint,
  'proposalId' : bigint,
  'voterPrincipal' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAnnouncement' : ActorMethod<
    [string, string, string],
    [] | [Announcement]
  >,
  'addChatMessage' : ActorMethod<[bigint, string, string], [] | [ChatMessage]>,
  'adminLogin' : ActorMethod<[string], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'castVote' : ActorMethod<[bigint, string, bigint, bigint], boolean>,
  'closeProposal' : ActorMethod<[string, bigint], boolean>,
  'createProposal' : ActorMethod<
    [string, string, string, Array<string>],
    [] | [Proposal]
  >,
  'deleteAnnouncement' : ActorMethod<[string, bigint], boolean>,
  'getAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatMessages' : ActorMethod<[bigint], Array<ChatMessage>>,
  'getManualBalances' : ActorMethod<
    [],
    {
      'icp' : string,
      'fund' : string,
      'bittyPriceUsd' : string,
      'bitty' : string,
    }
  >,
  'getProposals' : ActorMethod<[], Array<Proposal>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVotesForProposal' : ActorMethod<[bigint], Array<Vote>>,
  'hasVoted' : ActorMethod<[bigint, string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setManualBalances' : ActorMethod<[string, string, string], boolean>,
  'setManualBittyPrice' : ActorMethod<[string, string], boolean>,
  'setManualFundBalance' : ActorMethod<[string, string], boolean>,
  'updateAnnouncement' : ActorMethod<[string, bigint, string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];