/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'timestamp' : bigint,
}
export interface ChatMessage {
  'id' : bigint,
  'author' : string,
  'message' : string,
  'timestamp' : bigint,
  'proposalId' : bigint,
}
export interface Proposal {
  'id' : bigint,
  'startTime' : bigint,
  'title' : string,
  'endTime' : bigint,
  'description' : string,
  'isOpen' : boolean,
  'options' : Array<string>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vote {
  'weight' : bigint,
  'optionIndex' : bigint,
  'proposalId' : bigint,
  'voterPrincipal' : string,
}

export interface VoteType_ICP { 'ICP': null }
export interface VoteType_BITTYICP { 'BITTYICP': null }
export type VoteType = VoteType_ICP | VoteType_BITTYICP;

export interface MonthlyVote {
  id: bigint; voteType: VoteType; month: bigint; year: bigint;
  openTime: bigint; closeTime: bigint; isFinalized: boolean; totalVoteAmount: string;
}
export interface VoteAllocation {
  voteId: bigint; voterPrincipal: string; pctA: bigint; pctB: bigint; pctC: bigint; votingPower: bigint;
}
export interface VoteResult { optionLabel: string; totalWeightedPct: bigint; voterCount: bigint; }
export interface RewardsPoolEntry {
  voteId: bigint; voteType: VoteType; losingOptionLabel: string; losingOptionPct: bigint; poolAmount: string; distributed: boolean;
}
export interface CustomProposal {
  id: bigint; title: string; description: string; voteType: VoteType; options: string[];
  openTime: bigint; closeTime: bigint; isFinalized: boolean; totalVoteAmount: string;
}
export interface CustomOptionAlloc { optionIndex: bigint; pct: bigint; }
export interface CustomVoteAllocation {
  proposalId: bigint; voterPrincipal: string; allocations: CustomOptionAlloc[]; votingPower: bigint;
}
export interface CustomVoteResult { optionLabel: string; optionIndex: bigint; totalWeightedPct: bigint; voterCount: bigint; }
export interface CustomRewardsPoolEntry {
  proposalId: bigint; voteType: VoteType; losingOptionLabel: string; losingOptionPct: bigint; poolAmount: string; distributed: boolean;
}

export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAnnouncement' : ActorMethod<
    [string, string, string],
    [] | [Announcement]
  >,
  'addChatMessage' : ActorMethod<[bigint, string, string], [] | [ChatMessage]>,
  'adminLogin' : ActorMethod<[string], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'castVote' : ActorMethod<[bigint, string, bigint, bigint], boolean>,
  'closeProposal' : ActorMethod<[string, bigint], boolean>,
  'createProposal' : ActorMethod<
    [string, string, string, Array<string>],
    [] | [Proposal]
  >,
  'deleteAnnouncement' : ActorMethod<[string, bigint], boolean>,
  'getAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatMessages' : ActorMethod<[bigint], Array<ChatMessage>>,
  'getManualBalances' : ActorMethod<
    [],
    {
      'icp' : string,
      'fund' : string,
      'bittyPriceUsd' : string,
      'bitty' : string,
    }
  >,
  'getProposals' : ActorMethod<[], Array<Proposal>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVotesForProposal' : ActorMethod<[bigint], Array<Vote>>,
  'hasVoted' : ActorMethod<[bigint, string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setManualBalances' : ActorMethod<[string, string, string], boolean>,
  'setManualBittyPrice' : ActorMethod<[string, string], boolean>,
  'setManualFundBalance' : ActorMethod<[string, string], boolean>,
  'updateAnnouncement' : ActorMethod<[string, bigint, string, string], boolean>,
  getActiveVotes: ActorMethod<[], MonthlyVote[]>;
  getAllVotes: ActorMethod<[], MonthlyVote[]>;
  castSplitVote: ActorMethod<[bigint, string, bigint, bigint, bigint, bigint], boolean>;
  hasVotedOnVote: ActorMethod<[bigint, string], boolean>;
  getVoteAllocations: ActorMethod<[bigint], VoteAllocation[]>;
  getVoteResults: ActorMethod<[bigint], VoteResult[]>;
  setVoteAmount: ActorMethod<[string, bigint, string], boolean>;
  finalizeVote: ActorMethod<[string, bigint], boolean>;
  markRewardsDistributed: ActorMethod<[string, bigint], boolean>;
  getRewardsPools: ActorMethod<[], RewardsPoolEntry[]>;
  setNeuronTopupAddress: ActorMethod<[string, string], boolean>;
  setGamesWallet: ActorMethod<[string, string], boolean>;
  getAdminConfig: ActorMethod<[], { neuronTopupAddress: string; gamesWallet: string }>;
  createCustomProposal: ActorMethod<[string, string, string, VoteType, string[], bigint], [] | [CustomProposal]>;
  getCustomProposals: ActorMethod<[], CustomProposal[]>;
  castCustomVote: ActorMethod<[bigint, string, CustomOptionAlloc[], bigint], boolean>;
  hasVotedOnCustomProposal: ActorMethod<[bigint, string], boolean>;
  getCustomVoteAllocations: ActorMethod<[bigint], CustomVoteAllocation[]>;
  getCustomVoteResults: ActorMethod<[bigint], CustomVoteResult[]>;
  setCustomProposalAmount: ActorMethod<[string, bigint, string], boolean>;
  finalizeCustomProposal: ActorMethod<[string, bigint], boolean>;
  getCustomRewardsPools: ActorMethod<[], CustomRewardsPoolEntry[]>;
  markCustomRewardsDistributed: ActorMethod<[string, bigint], boolean>;
  initWalletVerification: ActorMethod<[string], { ok: bigint } | { err: string }>;
  confirmWalletVerification: ActorMethod<[string], { ok: null } | { err: string }>;
  getMyVerifiedWallets: ActorMethod<[], string[]>;
  isExternalWalletClaimed: ActorMethod<[string], boolean>;
  getWalletOwner: ActorMethod<[string], [] | [string]>;
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
