/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'timestamp' : bigint,
}
export interface ChatMessage {
  'id' : bigint,
  'voteId' : bigint,
  'author' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface CustomOptionAlloc { 'pct' : bigint, 'optionIndex' : bigint }
export interface CustomProposal {
  'id' : bigint,
  'title' : string,
  'closeTime' : bigint,
  'voteType' : VoteType,
  'totalVoteAmount' : string,
  'description' : string,
  'isFinalized' : boolean,
  'options' : Array<string>,
  'openTime' : bigint,
}
export interface CustomProposalMeta {
  'destinationAddress' : string,
  'voteAmount' : string,
  'proposalId' : bigint,
}
export interface CustomRewardsPoolEntry {
  'distributed' : boolean,
  'voteType' : VoteType,
  'losingOptionPct' : bigint,
  'losingOptionLabel' : string,
  'proposalId' : bigint,
  'poolAmount' : string,
}
export interface CustomVoteAllocation {
  'votingPower' : bigint,
  'allocations' : Array<CustomOptionAlloc>,
  'proposalId' : bigint,
  'voterPrincipal' : string,
}
export interface CustomVoteResult {
  'optionLabel' : string,
  'totalWeightedPct' : bigint,
  'optionIndex' : bigint,
  'voterCount' : bigint,
}
export interface MonthlyVote {
  'id' : bigint,
  'month' : bigint,
  'closeTime' : bigint,
  'voteType' : VoteType,
  'totalVoteAmount' : string,
  'year' : bigint,
  'isFinalized' : boolean,
  'openTime' : bigint,
}
export interface PendingDistribution {
  'title' : string,
  'voteType' : VoteType,
  'voteId' : bigint,
  'amountNeeded' : string,
  'isCustom' : boolean,
  'proposalId' : bigint,
}
export interface RewardTransaction {
  'id' : bigint,
  'recipient' : string,
  'voteId' : bigint,
  'timestamp' : bigint,
  'tokenType' : VoteType,
  'amount' : bigint,
  'voteTitle' : string,
  'proposalId' : bigint,
}
export interface RewardsPoolEntry {
  'distributed' : boolean,
  'voteType' : VoteType,
  'voteId' : bigint,
  'losingOptionPct' : bigint,
  'losingOptionLabel' : string,
  'poolAmount' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VoteAllocation {
  'votingPower' : bigint,
  'pctA' : bigint,
  'pctB' : bigint,
  'pctC' : bigint,
  'voteId' : bigint,
  'voterPrincipal' : string,
}
export interface VoteResult {
  'optionLabel' : string,
  'totalWeightedPct' : bigint,
  'voterCount' : bigint,
}
export type VoteType = { 'ICP' : null } |
  { 'BITTYICP' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAnnouncement' : ActorMethod<
    [string, string, string],
    [] | [Announcement]
  >,
  'addChatMessage' : ActorMethod<[bigint, string, string], [] | [ChatMessage]>,
  'adminLogin' : ActorMethod<[string], boolean>,
  'adminResetVerifiedWallets' : ActorMethod<[string], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'autoFinalizeExpired' : ActorMethod<[], undefined>,
  'castCustomVote' : ActorMethod<
    [bigint, string, Array<CustomOptionAlloc>, bigint],
    boolean
  >,
  'castSplitVote' : ActorMethod<
    [bigint, string, bigint, bigint, bigint, bigint],
    boolean
  >,
  'confirmWalletVerification' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'createCustomProposal' : ActorMethod<
    [string, string, string, VoteType, Array<string>, bigint, string, string],
    [] | [CustomProposal]
  >,
  'deleteAnnouncement' : ActorMethod<[string, bigint], boolean>,
  'distributeCustomRewards' : ActorMethod<
    [string, bigint],
    { 'errors' : Array<string>, 'success' : boolean, 'transferCount' : bigint }
  >,
  'distributeRewards' : ActorMethod<
    [string, bigint],
    { 'errors' : Array<string>, 'success' : boolean, 'transferCount' : bigint }
  >,
  'finalizeCustomProposal' : ActorMethod<[string, bigint], boolean>,
  'finalizeVote' : ActorMethod<[string, bigint], boolean>,
  'getActiveVotes' : ActorMethod<[], Array<MonthlyVote>>,
  'getAdminConfig' : ActorMethod<
    [],
    { 'gamesWallet' : string, 'neuronTopupAddress' : string }
  >,
  'getAllRewardTransactions' : ActorMethod<[string], Array<RewardTransaction>>,
  'getAllVotes' : ActorMethod<[], Array<MonthlyVote>>,
  'getAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getBittyUsdPrice' : ActorMethod<[], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCanisterBalance' : ActorMethod<
    [],
    { 'icpE8s' : bigint, 'bittyE8s' : bigint }
  >,
  'getChatMessages' : ActorMethod<[bigint], Array<ChatMessage>>,
  'getCustomProposalMeta' : ActorMethod<[bigint], [] | [CustomProposalMeta]>,
  'getCustomProposals' : ActorMethod<[], Array<CustomProposal>>,
  'getCustomRewardsPools' : ActorMethod<[], Array<CustomRewardsPoolEntry>>,
  'getCustomVoteAllocations' : ActorMethod<
    [bigint],
    Array<CustomVoteAllocation>
  >,
  'getCustomVoteResults' : ActorMethod<[bigint], Array<CustomVoteResult>>,
  'getIcpUsdPrice' : ActorMethod<[], string>,
  'getManualBalances' : ActorMethod<
    [],
    {
      'icp' : string,
      'fund' : string,
      'bittyPriceUsd' : string,
      'bitty' : string,
    }
  >,
  'getMyRewardTransactions' : ActorMethod<[string], Array<RewardTransaction>>,
  'getMyVerifiedWallets' : ActorMethod<[], Array<string>>,
  'getPendingDistributions' : ActorMethod<[], Array<PendingDistribution>>,
  'getRewardsPools' : ActorMethod<[], Array<RewardsPoolEntry>>,
  'getTotalRewardsDistributed' : ActorMethod<
    [],
    { 'totalICP' : bigint, 'totalBITTY' : bigint }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVoteAllocations' : ActorMethod<[bigint], Array<VoteAllocation>>,
  'getVoteResults' : ActorMethod<[bigint], Array<VoteResult>>,
  'getWalletOwner' : ActorMethod<[string], [] | [string]>,
  'hasVotedOnCustomProposal' : ActorMethod<[bigint, string], boolean>,
  'hasVotedOnVote' : ActorMethod<[bigint, string], boolean>,
  'initWalletVerification' : ActorMethod<
    [string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isExternalWalletClaimed' : ActorMethod<[string], boolean>,
  'markCustomRewardsDistributed' : ActorMethod<[string, bigint], boolean>,
  'markRewardsDistributed' : ActorMethod<[string, bigint], boolean>,
  'retryPendingDistributions' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setCustomProposalAmount' : ActorMethod<[string, bigint, string], boolean>,
  'setGamesWallet' : ActorMethod<[string, string], boolean>,
  'setManualBalances' : ActorMethod<[string, string, string], boolean>,
  'setManualBittyPrice' : ActorMethod<[string, string], boolean>,
  'setManualFundBalance' : ActorMethod<[string, string], boolean>,
  'setNeuronTopupAddress' : ActorMethod<[string, string], boolean>,
  'setVoteAmount' : ActorMethod<[string, bigint, string], boolean>,
  'setVoteAmountFromTreasury' : ActorMethod<[string, bigint, string], boolean>,
  'transformHttpResponse' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
  'unverifyWallet' : ActorMethod<[string], boolean>,
  'updateAnnouncement' : ActorMethod<[string, bigint, string, string], boolean>,
  'verifyExternalWallet' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];