/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ChatMessage {
    id: bigint;
    author: string;
    message: string;
    timestamp: bigint;
    proposalId: bigint;
}
export interface Announcement {
    id: bigint;
    title: string;
    body: string;
    timestamp: bigint;
}
export interface Vote {
    weight: bigint;
    optionIndex: bigint;
    proposalId: bigint;
    voterPrincipal: string;
}
export interface Proposal {
    id: bigint;
    startTime: bigint;
    title: string;
    endTime: bigint;
    description: string;
    isOpen: boolean;
    options: Array<string>;
}
export interface UserProfile {
    name: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAnnouncement(password: string, title: string, body: string): Promise<Announcement | null>;
    addChatMessage(proposalId: bigint, author: string, message: string): Promise<ChatMessage | null>;
    adminLogin(password: string): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    castVote(proposalId: bigint, voterPrincipal: string, optionIndex: bigint, weight: bigint): Promise<boolean>;
    closeProposal(password: string, proposalId: bigint): Promise<boolean>;
    createProposal(password: string, title: string, description: string, options: Array<string>): Promise<Proposal | null>;
    deleteAnnouncement(password: string, id: bigint): Promise<boolean>;
    getAnnouncements(): Promise<Array<Announcement>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChatMessages(proposalId: bigint): Promise<Array<ChatMessage>>;
    getManualBalances(): Promise<{
        icp: string;
        fund: string;
        bittyPriceUsd: string;
        bitty: string;
    }>;
    getProposals(): Promise<Array<Proposal>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVotesForProposal(proposalId: bigint): Promise<Array<Vote>>;
    hasVoted(proposalId: bigint, voterPrincipal: string): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setManualBalances(password: string, icp: string, bitty: string): Promise<boolean>;
    setManualBittyPrice(password: string, price: string): Promise<boolean>;
    setManualFundBalance(password: string, fund: string): Promise<boolean>;
    updateAnnouncement(password: string, id: bigint, title: string, body: string): Promise<boolean>;
    getActiveVotes(): Promise<any[]>;
    getAllVotes(): Promise<any[]>;
    castSplitVote(voteId: bigint, voterPrincipal: string, pctA: bigint, pctB: bigint, pctC: bigint, votingPower: bigint): Promise<boolean>;
    hasVotedOnVote(voteId: bigint, voterPrincipal: string): Promise<boolean>;
    getVoteAllocations(voteId: bigint): Promise<any[]>;
    getVoteResults(voteId: bigint): Promise<any[]>;
    setVoteAmount(password: string, voteId: bigint, amount: string): Promise<boolean>;
    finalizeVote(password: string, voteId: bigint): Promise<boolean>;
    markRewardsDistributed(password: string, voteId: bigint): Promise<boolean>;
    distributeRewards(password: string, voteId: bigint): Promise<{ success: boolean; transferCount: bigint; errors: string[] }>;
    distributeCustomRewards(password: string, proposalId: bigint): Promise<{ success: boolean; transferCount: bigint; errors: string[] }>;
    getRewardsPools(): Promise<any[]>;
    setNeuronTopupAddress(password: string, addr: string): Promise<boolean>;
    setGamesWallet(password: string, addr: string): Promise<boolean>;
    getAdminConfig(): Promise<{ neuronTopupAddress: string; gamesWallet: string }>;
    createCustomProposal(password: string, title: string, description: string, voteType: any, options: string[], closeTimeNs: bigint): Promise<any | null>;
    getCustomProposals(): Promise<any[]>;
    castCustomVote(proposalId: bigint, voterPrincipal: string, allocations: any[], votingPower: bigint): Promise<boolean>;
    hasVotedOnCustomProposal(proposalId: bigint, voterPrincipal: string): Promise<boolean>;
    getCustomVoteAllocations(proposalId: bigint): Promise<any[]>;
    getCustomVoteResults(proposalId: bigint): Promise<any[]>;
    setCustomProposalAmount(password: string, proposalId: bigint, amount: string): Promise<boolean>;
    finalizeCustomProposal(password: string, proposalId: bigint): Promise<boolean>;
    getCustomRewardsPools(): Promise<any[]>;
    markCustomRewardsDistributed(password: string, proposalId: bigint): Promise<boolean>;
    initWalletVerification(externalWallet: string): Promise<{ ok: bigint } | { err: string }>;
    confirmWalletVerification(externalWallet: string): Promise<{ ok: null } | { err: string }>;
    getMyVerifiedWallets(): Promise<string[]>;
    isExternalWalletClaimed(wallet: string): Promise<boolean>;
    getWalletOwner(wallet: string): Promise<string | null>;
    getIcpUsdPrice(): Promise<string>;
    getBittyUsdPrice(): Promise<string>;
}
import type { Announcement as _Announcement, ChatMessage as _ChatMessage, Proposal as _Proposal, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAnnouncement(arg0: string, arg1: string, arg2: string): Promise<Announcement | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addAnnouncement(arg0, arg1, arg2);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAnnouncement(arg0, arg1, arg2);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addChatMessage(arg0: bigint, arg1: string, arg2: string): Promise<ChatMessage | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addChatMessage(arg0, arg1, arg2);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChatMessage(arg0, arg1, arg2);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminLogin(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async castVote(arg0: bigint, arg1: string, arg2: bigint, arg3: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.castVote(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.castVote(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async closeProposal(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.closeProposal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.closeProposal(arg0, arg1);
            return result;
        }
    }
    async createProposal(arg0: string, arg1: string, arg2: string, arg3: Array<string>): Promise<Proposal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.createProposal(arg0, arg1, arg2, arg3);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProposal(arg0, arg1, arg2, arg3);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteAnnouncement(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnnouncement(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnnouncement(arg0, arg1);
            return result;
        }
    }
    async getAnnouncements(): Promise<Array<Announcement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnnouncements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnnouncements();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatMessages(arg0: bigint): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatMessages(arg0);
            return result;
        }
    }
    async getManualBalances(): Promise<{
        icp: string;
        fund: string;
        bittyPriceUsd: string;
        bitty: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getManualBalances();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getManualBalances();
            return result;
        }
    }
    async getProposals(): Promise<Array<Proposal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProposals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProposals();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVotesForProposal(arg0: bigint): Promise<Array<Vote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVotesForProposal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVotesForProposal(arg0);
            return result;
        }
    }
    async hasVoted(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasVoted(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasVoted(arg0, arg1);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setManualBalances(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setManualBalances(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setManualBalances(arg0, arg1, arg2);
            return result;
        }
    }
    async setManualBittyPrice(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setManualBittyPrice(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setManualBittyPrice(arg0, arg1);
            return result;
        }
    }
    async setManualFundBalance(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setManualFundBalance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setManualFundBalance(arg0, arg1);
            return result;
        }
    }
    async updateAnnouncement(arg0: string, arg1: bigint, arg2: string, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAnnouncement(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAnnouncement(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async getActiveVotes(): Promise<any[]> {
        const result = await this.actor.getActiveVotes();
        return result;
    }
    async getAllVotes(): Promise<any[]> {
        const result = await this.actor.getAllVotes();
        return result;
    }
    async castSplitVote(voteId: bigint, voterPrincipal: string, pctA: bigint, pctB: bigint, pctC: bigint, votingPower: bigint): Promise<boolean> {
        const result = await this.actor.castSplitVote(voteId, voterPrincipal, pctA, pctB, pctC, votingPower);
        return result;
    }
    async hasVotedOnVote(voteId: bigint, voterPrincipal: string): Promise<boolean> {
        const result = await this.actor.hasVotedOnVote(voteId, voterPrincipal);
        return result;
    }
    async getVoteAllocations(voteId: bigint): Promise<any[]> {
        const result = await this.actor.getVoteAllocations(voteId);
        return result;
    }
    async getVoteResults(voteId: bigint): Promise<any[]> {
        const result = await this.actor.getVoteResults(voteId);
        return result;
    }
    async setVoteAmount(password: string, voteId: bigint, amount: string): Promise<boolean> {
        const result = await this.actor.setVoteAmount(password, voteId, amount);
        return result;
    }
    async finalizeVote(password: string, voteId: bigint): Promise<boolean> {
        const result = await this.actor.finalizeVote(password, voteId);
        return result;
    }
    async markRewardsDistributed(password: string, voteId: bigint): Promise<boolean> {
        const result = await this.actor.markRewardsDistributed(password, voteId);
        return result;
    }
    async distributeRewards(password: string, voteId: bigint): Promise<{ success: boolean; transferCount: bigint; errors: string[] }> {
        const result = await this.actor.distributeRewards(password, voteId);
        return result;
    }
    async distributeCustomRewards(password: string, proposalId: bigint): Promise<{ success: boolean; transferCount: bigint; errors: string[] }> {
        const result = await this.actor.distributeCustomRewards(password, proposalId);
        return result;
    }
    async getRewardsPools(): Promise<any[]> {
        const result = await this.actor.getRewardsPools();
        return result;
    }
    async setNeuronTopupAddress(password: string, addr: string): Promise<boolean> {
        const result = await this.actor.setNeuronTopupAddress(password, addr);
        return result;
    }
    async setGamesWallet(password: string, addr: string): Promise<boolean> {
        const result = await this.actor.setGamesWallet(password, addr);
        return result;
    }
    async getAdminConfig(): Promise<{ neuronTopupAddress: string; gamesWallet: string }> {
        const result = await this.actor.getAdminConfig();
        return result;
    }
    async createCustomProposal(password: string, title: string, description: string, voteType: any, options: string[], closeTimeNs: bigint): Promise<any | null> {
        const result = await this.actor.createCustomProposal(password, title, description, voteType, options, closeTimeNs);
        return result.length === 0 ? null : result[0];
    }
    async getCustomProposals(): Promise<any[]> {
        const result = await this.actor.getCustomProposals();
        return result;
    }
    async castCustomVote(proposalId: bigint, voterPrincipal: string, allocations: any[], votingPower: bigint): Promise<boolean> {
        const result = await this.actor.castCustomVote(proposalId, voterPrincipal, allocations, votingPower);
        return result;
    }
    async hasVotedOnCustomProposal(proposalId: bigint, voterPrincipal: string): Promise<boolean> {
        const result = await this.actor.hasVotedOnCustomProposal(proposalId, voterPrincipal);
        return result;
    }
    async getCustomVoteAllocations(proposalId: bigint): Promise<any[]> {
        const result = await this.actor.getCustomVoteAllocations(proposalId);
        return result;
    }
    async getCustomVoteResults(proposalId: bigint): Promise<any[]> {
        const result = await this.actor.getCustomVoteResults(proposalId);
        return result;
    }
    async setCustomProposalAmount(password: string, proposalId: bigint, amount: string): Promise<boolean> {
        const result = await this.actor.setCustomProposalAmount(password, proposalId, amount);
        return result;
    }
    async finalizeCustomProposal(password: string, proposalId: bigint): Promise<boolean> {
        const result = await this.actor.finalizeCustomProposal(password, proposalId);
        return result;
    }
    async getCustomRewardsPools(): Promise<any[]> {
        const result = await this.actor.getCustomRewardsPools();
        return result;
    }
    async markCustomRewardsDistributed(password: string, proposalId: bigint): Promise<boolean> {
        const result = await this.actor.markCustomRewardsDistributed(password, proposalId);
        return result;
    }
    async initWalletVerification(externalWallet: string): Promise<{ ok: bigint } | { err: string }> {
        const result = await this.actor.initWalletVerification(externalWallet);
        return result;
    }
    async confirmWalletVerification(externalWallet: string): Promise<{ ok: null } | { err: string }> {
        const result = await this.actor.confirmWalletVerification(externalWallet);
        return result;
    }
    async getMyVerifiedWallets(): Promise<string[]> {
        const result = await this.actor.getMyVerifiedWallets();
        return result;
    }
    async isExternalWalletClaimed(wallet: string): Promise<boolean> {
        const result = await this.actor.isExternalWalletClaimed(wallet);
        return result;
    }
    async getWalletOwner(wallet: string): Promise<string | null> {
        const result = await this.actor.getWalletOwner(wallet);
        return result.length === 0 ? null : result[0];
    }
    async verifyExternalWallet(externalWallet: string): Promise<{ ok: null } | { err: string }> {
        const result = await this.actor.verifyExternalWallet(externalWallet);
        return result;
    }
    async adminResetVerifiedWallets(password: string): Promise<boolean> {
        const result = await this.actor.adminResetVerifiedWallets(password);
        return result;
    }
    async unverifyWallet(externalWallet: string): Promise<boolean> {
        const result = await this.actor.unverifyWallet(externalWallet);
        return result;
    }
    async getIcpUsdPrice(): Promise<string> {
        const result = await this.actor.getIcpUsdPrice();
        return result;
    }
    async getBittyUsdPrice(): Promise<string> {
        const result = await this.actor.getBittyUsdPrice();
        return result;
    }
}
function from_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Announcement]): Announcement | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ChatMessage]): ChatMessage | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Proposal]): Proposal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
