/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CustomVoteAllocation {
    votingPower: bigint;
    allocations: Array<CustomOptionAlloc>;
    proposalId: bigint;
    voterPrincipal: string;
}
export interface CustomVoteResult {
    optionLabel: string;
    totalWeightedPct: bigint;
    optionIndex: bigint;
    voterCount: bigint;
}
export interface CustomOptionAlloc {
    pct: bigint;
    optionIndex: bigint;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface CustomRewardsPoolEntry {
    distributed: boolean;
    voteType: VoteType;
    losingOptionPct: bigint;
    losingOptionLabel: string;
    proposalId: bigint;
    poolAmount: string;
}
export interface VoteResult {
    optionLabel: string;
    totalWeightedPct: bigint;
    voterCount: bigint;
}
export interface RewardsPoolEntry {
    distributed: boolean;
    voteType: VoteType;
    voteId: bigint;
    losingOptionPct: bigint;
    losingOptionLabel: string;
    poolAmount: string;
}
export interface MonthlyVote {
    id: bigint;
    month: bigint;
    closeTime: bigint;
    voteType: VoteType;
    totalVoteAmount: string;
    year: bigint;
    isFinalized: boolean;
    openTime: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface VoteAllocation {
    votingPower: bigint;
    pctA: bigint;
    pctB: bigint;
    pctC: bigint;
    voteId: bigint;
    voterPrincipal: string;
}
export interface RewardTransaction {
    id: bigint;
    recipient: string;
    voteId: bigint;
    timestamp: bigint;
    tokenType: VoteType;
    amount: bigint;
    voteTitle: string;
    proposalId: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Announcement {
    id: bigint;
    title: string;
    body: string;
    timestamp: bigint;
}
export interface ChatMessage {
    id: bigint;
    voteId: bigint;
    author: string;
    message: string;
    timestamp: bigint;
}
export interface CustomProposalMeta {
    destinationAddress: string;
    voteAmount: string;
    proposalId: bigint;
}
export interface CustomProposal {
    id: bigint;
    title: string;
    closeTime: bigint;
    voteType: VoteType;
    totalVoteAmount: string;
    description: string;
    isFinalized: boolean;
    options: Array<string>;
    openTime: bigint;
}
export interface PendingDistribution {
    title: string;
    voteType: VoteType;
    voteId: bigint;
    amountNeeded: string;
    isCustom: boolean;
    proposalId: bigint;
}
export interface UserProfile {
    name: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VoteType {
    ICP = "ICP",
    BITTYICP = "BITTYICP"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAnnouncement(password: string, title: string, body: string): Promise<Announcement | null>;
    addChatMessage(voteId: bigint, author: string, message: string): Promise<ChatMessage | null>;
    adminLogin(password: string): Promise<boolean>;
    adminResetVerifiedWallets(password: string): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    autoFinalizeExpired(): Promise<void>;
    castCustomVote(proposalId: bigint, voterPrincipal: string, allocations: Array<CustomOptionAlloc>, votingPower: bigint): Promise<boolean>;
    castSplitVote(voteId: bigint, voterPrincipal: string, pctA: bigint, pctB: bigint, pctC: bigint, votingPower: bigint): Promise<boolean>;
    confirmWalletVerification(externalWallet: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createCustomProposal(password: string, title: string, description: string, voteType: VoteType, options: Array<string>, closeTimeNs: bigint, voteAmount: string, destinationAddress: string): Promise<CustomProposal | null>;
    deleteAnnouncement(password: string, id: bigint): Promise<boolean>;
    distributeCustomRewards(password: string, proposalId: bigint): Promise<{
        errors: Array<string>;
        success: boolean;
        transferCount: bigint;
    }>;
    distributeRewards(password: string, voteId: bigint): Promise<{
        errors: Array<string>;
        success: boolean;
        transferCount: bigint;
    }>;
    finalizeCustomProposal(password: string, proposalId: bigint): Promise<boolean>;
    finalizeVote(password: string, voteId: bigint): Promise<boolean>;
    getActiveVotes(): Promise<Array<MonthlyVote>>;
    getAdminConfig(): Promise<{
        gamesWallet: string;
        neuronTopupAddress: string;
    }>;
    getAllRewardTransactions(password: string): Promise<Array<RewardTransaction>>;
    getAllVotes(): Promise<Array<MonthlyVote>>;
    getAnnouncements(): Promise<Array<Announcement>>;
    getBittyUsdPrice(): Promise<string>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCanisterBalance(): Promise<{
        icpE8s: bigint;
        bittyE8s: bigint;
    }>;
    getChatMessages(voteId: bigint): Promise<Array<ChatMessage>>;
    getCustomProposalMeta(proposalId: bigint): Promise<CustomProposalMeta | null>;
    getCustomProposals(): Promise<Array<CustomProposal>>;
    getCustomRewardsPools(): Promise<Array<CustomRewardsPoolEntry>>;
    getCustomVoteAllocations(proposalId: bigint): Promise<Array<CustomVoteAllocation>>;
    getCustomVoteResults(proposalId: bigint): Promise<Array<CustomVoteResult>>;
    getIcpUsdPrice(): Promise<string>;
    getManualBalances(): Promise<{
        icp: string;
        fund: string;
        bittyPriceUsd: string;
        bitty: string;
    }>;
    getMyRewardTransactions(principal: string): Promise<Array<RewardTransaction>>;
    getMyVerifiedWallets(): Promise<Array<string>>;
    getPendingDistributions(): Promise<Array<PendingDistribution>>;
    getRewardsPools(): Promise<Array<RewardsPoolEntry>>;
    getTotalRewardsDistributed(): Promise<{
        totalICP: bigint;
        totalBITTY: bigint;
    }>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVoteAllocations(voteId: bigint): Promise<Array<VoteAllocation>>;
    getVoteResults(voteId: bigint): Promise<Array<VoteResult>>;
    getWalletOwner(wallet: string): Promise<string | null>;
    hasVotedOnCustomProposal(proposalId: bigint, voterPrincipal: string): Promise<boolean>;
    hasVotedOnVote(voteId: bigint, voterPrincipal: string): Promise<boolean>;
    initWalletVerification(externalWallet: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }>;
    isCallerAdmin(): Promise<boolean>;
    isExternalWalletClaimed(wallet: string): Promise<boolean>;
    markCustomRewardsDistributed(password: string, proposalId: bigint): Promise<boolean>;
    markRewardsDistributed(password: string, voteId: bigint): Promise<boolean>;
    retryPendingDistributions(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setCustomProposalAmount(password: string, proposalId: bigint, amount: string): Promise<boolean>;
    setGamesWallet(password: string, addr: string): Promise<boolean>;
    setManualBalances(password: string, icp: string, bitty: string): Promise<boolean>;
    setManualBittyPrice(password: string, price: string): Promise<boolean>;
    setManualFundBalance(password: string, fund: string): Promise<boolean>;
    setNeuronTopupAddress(password: string, addr: string): Promise<boolean>;
    setVoteAmount(password: string, voteId: bigint, amount: string): Promise<boolean>;
    setVoteAmountFromTreasury(password: string, voteId: bigint, amount: string): Promise<boolean>;
    transformHttpResponse(input: TransformationInput): Promise<TransformationOutput>;
    unverifyWallet(externalWallet: string): Promise<boolean>;
    updateAnnouncement(password: string, id: bigint, title: string, body: string): Promise<boolean>;
    verifyExternalWallet(externalWallet: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { Announcement as _Announcement, ChatMessage as _ChatMessage, CustomProposal as _CustomProposal, CustomProposalMeta as _CustomProposalMeta, CustomRewardsPoolEntry as _CustomRewardsPoolEntry, MonthlyVote as _MonthlyVote, PendingDistribution as _PendingDistribution, RewardTransaction as _RewardTransaction, RewardsPoolEntry as _RewardsPoolEntry, UserProfile as _UserProfile, UserRole as _UserRole, VoteType as _VoteType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAnnouncement(arg0: string, arg1: string, arg2: string): Promise<Announcement | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addAnnouncement(arg0, arg1, arg2);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAnnouncement(arg0, arg1, arg2);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addChatMessage(arg0: bigint, arg1: string, arg2: string): Promise<ChatMessage | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addChatMessage(arg0, arg1, arg2);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChatMessage(arg0, arg1, arg2);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminLogin(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0);
            return result;
        }
    }
    async adminResetVerifiedWallets(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminResetVerifiedWallets(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminResetVerifiedWallets(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async autoFinalizeExpired(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.autoFinalizeExpired();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.autoFinalizeExpired();
            return result;
        }
    }
    async castCustomVote(arg0: bigint, arg1: string, arg2: Array<CustomOptionAlloc>, arg3: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.castCustomVote(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.castCustomVote(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async castSplitVote(arg0: bigint, arg1: string, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.castSplitVote(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.castSplitVote(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async confirmWalletVerification(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmWalletVerification(arg0);
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmWalletVerification(arg0);
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCustomProposal(arg0: string, arg1: string, arg2: string, arg3: VoteType, arg4: Array<string>, arg5: bigint, arg6: string, arg7: string): Promise<CustomProposal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomProposal(arg0, arg1, arg2, to_candid_VoteType_n6(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomProposal(arg0, arg1, arg2, to_candid_VoteType_n6(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteAnnouncement(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnnouncement(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnnouncement(arg0, arg1);
            return result;
        }
    }
    async distributeCustomRewards(arg0: string, arg1: bigint): Promise<{
        errors: Array<string>;
        success: boolean;
        transferCount: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.distributeCustomRewards(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.distributeCustomRewards(arg0, arg1);
            return result;
        }
    }
    async distributeRewards(arg0: string, arg1: bigint): Promise<{
        errors: Array<string>;
        success: boolean;
        transferCount: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.distributeRewards(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.distributeRewards(arg0, arg1);
            return result;
        }
    }
    async finalizeCustomProposal(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.finalizeCustomProposal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.finalizeCustomProposal(arg0, arg1);
            return result;
        }
    }
    async finalizeVote(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.finalizeVote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.finalizeVote(arg0, arg1);
            return result;
        }
    }
    async getActiveVotes(): Promise<Array<MonthlyVote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveVotes();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveVotes();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminConfig(): Promise<{
        gamesWallet: string;
        neuronTopupAddress: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminConfig();
            return result;
        }
    }
    async getAllRewardTransactions(arg0: string): Promise<Array<RewardTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRewardTransactions(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRewardTransactions(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllVotes(): Promise<Array<MonthlyVote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVotes();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVotes();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnnouncements(): Promise<Array<Announcement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnnouncements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnnouncements();
            return result;
        }
    }
    async getBittyUsdPrice(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getBittyUsdPrice();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBittyUsdPrice();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCanisterBalance(): Promise<{
        icpE8s: bigint;
        bittyE8s: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCanisterBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCanisterBalance();
            return result;
        }
    }
    async getChatMessages(arg0: bigint): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatMessages(arg0);
            return result;
        }
    }
    async getCustomProposalMeta(arg0: bigint): Promise<CustomProposalMeta | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomProposalMeta(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomProposalMeta(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomProposals(): Promise<Array<CustomProposal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomProposals();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomProposals();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomRewardsPools(): Promise<Array<CustomRewardsPoolEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomRewardsPools();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomRewardsPools();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomVoteAllocations(arg0: bigint): Promise<Array<CustomVoteAllocation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomVoteAllocations(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomVoteAllocations(arg0);
            return result;
        }
    }
    async getCustomVoteResults(arg0: bigint): Promise<Array<CustomVoteResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomVoteResults(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomVoteResults(arg0);
            return result;
        }
    }
    async getIcpUsdPrice(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getIcpUsdPrice();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIcpUsdPrice();
            return result;
        }
    }
    async getManualBalances(): Promise<{
        icp: string;
        fund: string;
        bittyPriceUsd: string;
        bitty: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getManualBalances();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getManualBalances();
            return result;
        }
    }
    async getMyRewardTransactions(arg0: string): Promise<Array<RewardTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRewardTransactions(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRewardTransactions(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyVerifiedWallets(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyVerifiedWallets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyVerifiedWallets();
            return result;
        }
    }
    async getPendingDistributions(): Promise<Array<PendingDistribution>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingDistributions();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingDistributions();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRewardsPools(): Promise<Array<RewardsPoolEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRewardsPools();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRewardsPools();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalRewardsDistributed(): Promise<{
        totalICP: bigint;
        totalBITTY: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalRewardsDistributed();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalRewardsDistributed();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVoteAllocations(arg0: bigint): Promise<Array<VoteAllocation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVoteAllocations(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVoteAllocations(arg0);
            return result;
        }
    }
    async getVoteResults(arg0: bigint): Promise<Array<VoteResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVoteResults(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVoteResults(arg0);
            return result;
        }
    }
    async getWalletOwner(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWalletOwner(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWalletOwner(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasVotedOnCustomProposal(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasVotedOnCustomProposal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasVotedOnCustomProposal(arg0, arg1);
            return result;
        }
    }
    async hasVotedOnVote(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasVotedOnVote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasVotedOnVote(arg0, arg1);
            return result;
        }
    }
    async initWalletVerification(arg0: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.initWalletVerification(arg0);
                return from_candid_variant_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initWalletVerification(arg0);
            return from_candid_variant_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isExternalWalletClaimed(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isExternalWalletClaimed(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isExternalWalletClaimed(arg0);
            return result;
        }
    }
    async markCustomRewardsDistributed(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markCustomRewardsDistributed(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markCustomRewardsDistributed(arg0, arg1);
            return result;
        }
    }
    async markRewardsDistributed(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markRewardsDistributed(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markRewardsDistributed(arg0, arg1);
            return result;
        }
    }
    async retryPendingDistributions(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.retryPendingDistributions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.retryPendingDistributions();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setCustomProposalAmount(arg0: string, arg1: bigint, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setCustomProposalAmount(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCustomProposalAmount(arg0, arg1, arg2);
            return result;
        }
    }
    async setGamesWallet(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setGamesWallet(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setGamesWallet(arg0, arg1);
            return result;
        }
    }
    async setManualBalances(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setManualBalances(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setManualBalances(arg0, arg1, arg2);
            return result;
        }
    }
    async setManualBittyPrice(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setManualBittyPrice(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setManualBittyPrice(arg0, arg1);
            return result;
        }
    }
    async setManualFundBalance(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setManualFundBalance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setManualFundBalance(arg0, arg1);
            return result;
        }
    }
    async setNeuronTopupAddress(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setNeuronTopupAddress(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setNeuronTopupAddress(arg0, arg1);
            return result;
        }
    }
    async setVoteAmount(arg0: string, arg1: bigint, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setVoteAmount(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setVoteAmount(arg0, arg1, arg2);
            return result;
        }
    }
    async setVoteAmountFromTreasury(arg0: string, arg1: bigint, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setVoteAmountFromTreasury(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setVoteAmountFromTreasury(arg0, arg1, arg2);
            return result;
        }
    }
    async transformHttpResponse(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transformHttpResponse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformHttpResponse(arg0);
            return result;
        }
    }
    async unverifyWallet(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.unverifyWallet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unverifyWallet(arg0);
            return result;
        }
    }
    async updateAnnouncement(arg0: string, arg1: bigint, arg2: string, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAnnouncement(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAnnouncement(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async verifyExternalWallet(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyExternalWallet(arg0);
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyExternalWallet(arg0);
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_CustomProposal_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomProposal): CustomProposal {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_CustomRewardsPoolEntry_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomRewardsPoolEntry): CustomRewardsPoolEntry {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_MonthlyVote_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MonthlyVote): MonthlyVote {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_PendingDistribution_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PendingDistribution): PendingDistribution {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_RewardTransaction_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RewardTransaction): RewardTransaction {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_RewardsPoolEntry_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RewardsPoolEntry): RewardsPoolEntry {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_VoteType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VoteType): VoteType {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Announcement]): Announcement | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ChatMessage]): ChatMessage | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CustomProposalMeta]): CustomProposalMeta | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CustomProposal]): CustomProposal | null {
    return value.length === 0 ? null : from_candid_CustomProposal_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    closeTime: bigint;
    voteType: _VoteType;
    totalVoteAmount: string;
    description: string;
    isFinalized: boolean;
    options: Array<string>;
    openTime: bigint;
}): {
    id: bigint;
    title: string;
    closeTime: bigint;
    voteType: VoteType;
    totalVoteAmount: string;
    description: string;
    isFinalized: boolean;
    options: Array<string>;
    openTime: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        closeTime: value.closeTime,
        voteType: from_candid_VoteType_n11(_uploadFile, _downloadFile, value.voteType),
        totalVoteAmount: value.totalVoteAmount,
        description: value.description,
        isFinalized: value.isFinalized,
        options: value.options,
        openTime: value.openTime
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    month: bigint;
    closeTime: bigint;
    voteType: _VoteType;
    totalVoteAmount: string;
    year: bigint;
    isFinalized: boolean;
    openTime: bigint;
}): {
    id: bigint;
    month: bigint;
    closeTime: bigint;
    voteType: VoteType;
    totalVoteAmount: string;
    year: bigint;
    isFinalized: boolean;
    openTime: bigint;
} {
    return {
        id: value.id,
        month: value.month,
        closeTime: value.closeTime,
        voteType: from_candid_VoteType_n11(_uploadFile, _downloadFile, value.voteType),
        totalVoteAmount: value.totalVoteAmount,
        year: value.year,
        isFinalized: value.isFinalized,
        openTime: value.openTime
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    recipient: string;
    voteId: bigint;
    timestamp: bigint;
    tokenType: _VoteType;
    amount: bigint;
    voteTitle: string;
    proposalId: bigint;
}): {
    id: bigint;
    recipient: string;
    voteId: bigint;
    timestamp: bigint;
    tokenType: VoteType;
    amount: bigint;
    voteTitle: string;
    proposalId: bigint;
} {
    return {
        id: value.id,
        recipient: value.recipient,
        voteId: value.voteId,
        timestamp: value.timestamp,
        tokenType: from_candid_VoteType_n11(_uploadFile, _downloadFile, value.tokenType),
        amount: value.amount,
        voteTitle: value.voteTitle,
        proposalId: value.proposalId
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    distributed: boolean;
    voteType: _VoteType;
    losingOptionPct: bigint;
    losingOptionLabel: string;
    proposalId: bigint;
    poolAmount: string;
}): {
    distributed: boolean;
    voteType: VoteType;
    losingOptionPct: bigint;
    losingOptionLabel: string;
    proposalId: bigint;
    poolAmount: string;
} {
    return {
        distributed: value.distributed,
        voteType: from_candid_VoteType_n11(_uploadFile, _downloadFile, value.voteType),
        losingOptionPct: value.losingOptionPct,
        losingOptionLabel: value.losingOptionLabel,
        proposalId: value.proposalId,
        poolAmount: value.poolAmount
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    voteType: _VoteType;
    voteId: bigint;
    amountNeeded: string;
    isCustom: boolean;
    proposalId: bigint;
}): {
    title: string;
    voteType: VoteType;
    voteId: bigint;
    amountNeeded: string;
    isCustom: boolean;
    proposalId: bigint;
} {
    return {
        title: value.title,
        voteType: from_candid_VoteType_n11(_uploadFile, _downloadFile, value.voteType),
        voteId: value.voteId,
        amountNeeded: value.amountNeeded,
        isCustom: value.isCustom,
        proposalId: value.proposalId
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    distributed: boolean;
    voteType: _VoteType;
    voteId: bigint;
    losingOptionPct: bigint;
    losingOptionLabel: string;
    poolAmount: string;
}): {
    distributed: boolean;
    voteType: VoteType;
    voteId: bigint;
    losingOptionPct: bigint;
    losingOptionLabel: string;
    poolAmount: string;
} {
    return {
        distributed: value.distributed,
        voteType: from_candid_VoteType_n11(_uploadFile, _downloadFile, value.voteType),
        voteId: value.voteId,
        losingOptionPct: value.losingOptionPct,
        losingOptionLabel: value.losingOptionLabel,
        poolAmount: value.poolAmount
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ICP: null;
} | {
    BITTYICP: null;
}): VoteType {
    return "ICP" in value ? VoteType.ICP : "BITTYICP" in value ? VoteType.BITTYICP : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MonthlyVote>): Array<MonthlyVote> {
    return value.map((x)=>from_candid_MonthlyVote_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RewardTransaction>): Array<RewardTransaction> {
    return value.map((x)=>from_candid_RewardTransaction_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CustomProposal>): Array<CustomProposal> {
    return value.map((x)=>from_candid_CustomProposal_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CustomRewardsPoolEntry>): Array<CustomRewardsPoolEntry> {
    return value.map((x)=>from_candid_CustomRewardsPoolEntry_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PendingDistribution>): Array<PendingDistribution> {
    return value.map((x)=>from_candid_PendingDistribution_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RewardsPoolEntry>): Array<RewardsPoolEntry> {
    return value.map((x)=>from_candid_RewardsPoolEntry_n31(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_VoteType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VoteType): _VoteType {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VoteType): {
    ICP: null;
} | {
    BITTYICP: null;
} {
    return value == VoteType.ICP ? {
        ICP: null
    } : value == VoteType.BITTYICP ? {
        BITTYICP: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
